@startuml 診察券保持者・ゲスト
[*] --> TOPページ
TOPページ -right-> ゲスト画面:　ゲスト
ゲスト画面 -right-> 入力内容確認画面:　確認する
入力内容確認画面 --> 予約完了画面:　登録する
TOPページ --> アカウント新規登録画面:　新規登録
TOPページ --> ログイン画面:　ログイン
アカウント新規登録画面 -right-> アカウント登録入力内容確認:　確認する
アカウント登録入力内容確認 -right-> ログイン画面:　登録する
ログイン画面 -right-> 日付選択画面:　ログイン
日付選択画面 -right-> 診察券保持者症状登録:　決定
診察券保持者症状登録 -right-> 予約内容確認画面:　登録する
予約内容確認画面 -right-> 予約完了画面:　登録する
ログイン画面 --> 予約後確認画面:　※予約完了後
予約後確認画面 --> 予約内容編集画面:　変更
予約後確認画面 -right-> 消去確認画面:　取り消し
消去確認画面 -right-> 予約内容消去画面:　予約を取り消す

@enduml