@startuml 診察券保持者・ゲスト
[*] --> TOPページ
TOPページ -right-> ゲスト画面:　ゲスト
ゲスト画面 -right-> 入力内容確認画面:　確認する
TOPページ --> 新規登録画面
TOPページ --> ログイン画面
新規登録画面 -right-> ログイン画面
ログイン画面 -right-> 日付選択画面
日付選択画面 -right-> 症状登録画面
症状登録画面 -right-> 予約内容確認画面
ログイン画面 --> 確認画面:　完了後
確認画面 -right-> 編集
確認画面 --> 削除
@enduml