@startuml 演習
hide footbox
Actor ":ユーザ" as user
participant ":ブラウザ" as browser
participant ":Webサーバ-" as web
participant ":画像サーバー" as image
activate user
user -> browser : リンクボタンを押す
activate browser
browser -> web : 画像ファイル名を伝える
activate web
web -> image : 該当する画像ファイルを探す
opt 画像ファイル発見
activate image
web <-- image : 閲覧可能状態にする
deactivate image
end alt                    
browser <- web : 画像ファイル
deactivate web
user <- browser : 画像ファイルを再生する
@enduml