@startuml 演習
|顧客|
|給仕|
|料理人|
|顧客|
start
:案内を依頼する;
|給仕|
:テーブルに案内する;
:メニューを渡す;
|顧客|
:メニュー;
:注文を決める;
|給仕|
:注文;
fork
:注文を受ける;
fork again
:伝票を書く;
end fork
:料理人に注文を伝える;
|料理人|
:注文を受ける;
:料理;
|給仕|
:料理を運ぶ;
fork
:料理;
fork again
:伝票;
end fork
:伝票を渡す;
|顧客|
:料理を食べる;
:代金を払う;
stop
@enduml