@startuml 演習
left to right direction
class 注文明細{
    合計
}
class 注文{
    数量
    小計
}
class 割引クーポン{
    値引き額
    期限
}
class カップ{
    サイズ
}
class ドリンク{
    種別
}
class 商品{
    名称
    単価
}
class フード{}
class レシピ{}
class 材料{}
class ハンバーガー{
    種別
}
class ポテト{
    サイズ
}
注文明細 "1..." o-- "*" 注文
注文 "0..." -- "1" 割引クーポン
注文 "0..." -right- "*" 商品
ドリンク --|> 商品
カップ "0" -- "*" ドリンク
フード -left-|> 商品
フード "1" -- "1" レシピ
ハンバーガー --|> フード
ポテト -left-|> フード
材料 "1" --|> "*" ハンバーガー
パン --|> 材料
肉 --|> 材料
野菜 --|> 材料
チーズ --|> 材料


@enduml